SELECT * FROM EMPLOYEES

SELECT F_NAME,l_NAME,SALARY,DEP_ID  FROM EMPLOYEES 
WHERE SALARY <(SELECT AVG(SALARY)FROM EMPLOYEES)
**SUBQUERY IN WHERE FROM **//

SELECT EMP_ID, SALARY ,(SELECT MAX(SALARY)FROM EMPLOYEES)AS MAX_SALARY
FROM EMPLOYEES
SUBQUERY IN SELECT  FROM *//


SELECT * FROM(SELECT F_NAME,L_NAME,EMP_ID FROM EMPLOYEES)AS EMP4ALL